### PR TITLE
Global CRUD firebase actions

### PR DESCRIPTION
**Pull request by Aleksalje**
Moved firebase actions to global module, onSnapshot can be attached/detached to any db collection needed.
CRUD operations will rarely change so it makes sense not to duplicate the actions. We could pass additional/optional data to those actions like callback actions, etc..
Does this make sense? :) 
The only thing that is bothering me is the notification cb implementation. :P 
Suggestions are welcome :)

### CODE REVIEW

**Review by MilosPaunovic — APPROVED** [review]

**Comment by MilosPaunovic** [comment]
Yes, it does make much sense - this is a great contribution @Aleksalje! Take a look at changes after merge @jelenamilanovic, cause this might affect your future work.

What exactly is bothering you with the `notifications`, help me understand better @Aleksalje ?

**Comment by Aleksalje** [comment]
> What exactly is bothering you with the `notifications`, help me understand better @Aleksalje ?
I don't like the way it's being passed to the action :D

**Comment by MilosPaunovic** [comment]
Okay, do you have any proposal for improvement? @Aleksalje

**Comment by jelenamilanovic** [comment]
@Aleksalje , @MilosPaunovic , we can return additional Promise from the action to the component and then call notification directly there. Another possible solution is to pass callback functions from component to action. These callbacks would define which notification to call and what message to display.

**Comment by Aleksalje** [comment]
Great idea @jelenamilanovic. 
I've added the `callback` and `message`  as optional parameters, If `message` parameter is not provided default message is displayed for different operations.
@MilosPaunovic @jelenamilanovic do you think this is a better approach?

**Review by MilosPaunovic — APPROVED** [review]

**Comment by MilosPaunovic** [comment]
Yes, definitely! Great work @Aleksalje; approved and merged.

**Pull request merged**
